server:
  port: 8888

spring:
  cloud:
    gateway:
      default-filters:
        -  TokenRelay
  datasource:
    url: jdbc:postgresql://postgres:5432/routedb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin123
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/auth-demo

keycloak:
  token-uri: http://keycloak:8080/realms/auth-demo/protocol/openid-connect/token
  client-id: springboot-client
  client-secret: springboot-secret-123

logging:
  level:
    liquibase: INFO
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
