services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_LOG_LEVEL: info
    ports:
      - "8080:8080"
    depends_on:
      - db
    command:
      - start-dev
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json

  customer-service:
    build:
      context: /customer-service

  auth-service:
    build:
      context: /auth-service
    ports:
      - "8888:8888"

volumes:
  pgdata:
