services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_DB: dev-mem
      KC_LOG_LEVEL: info
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./config:/opt/keycloak/data/import

  customer-service:
    build:
      context: /customer-service

  auth-service:
    build:
      context: /auth-service
    ports:
      - "8888:8888"