server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://keycloak:8080/realms/auth-demo
  application:
    name: customer-service
  cloud:
    config:
      enabled: false
logging:
  level:
    org.springframework.security:  DEBUG
