server:
  port: 8081
spring:
  application:
    name: customer-service
  cloud:
    config:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

